[plugins]
enabled = [
  "jamesfeeder/special-workspaces",
  "k4n4t4/hypr-submap",
  "thepunkoff/pomodoro",
]


[plugin_settings."thepunkoff/pomodoro"]
work-duration = 45
short-break-duration = 2
long-break-duration = 0
sessions-before-long-break = 20
auto-start-work = false
auto-start-breaks = false
panel_open_near_click = false
panel_placement = "floating"
panel_position = "center"
use-bundled-alarm-sound = true
bypass-noctalia-sound-globals = true


[notification.filter.pomodoro]
match = "noctalia"
match_content = "Pomodoro Timer"
play_sound = false
